hamji/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from polls.views import base_views

from . import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"questions", base_views.QuestionViewSet)

urlpatterns = [
    path("_api/", include(router.urls)),
    path("polls/", include("polls.urls")),
    path("common/", include("common.urls")),
    path("admin/", admin.site.urls),
    # path("", base_views.index, name='index'),
]

polls/urls.py
from django.urls import path
from .views import base_views, comment_views
from . import views

app_name = 'polls'
urlpatterns = [
    # base_views.py
    # path('', base_views.index, name='index'),
    path('', base_views.IndexView.as_view(), name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    # path('<int:pk>', base_views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/results/', base_views.result, name='results'),
    # path('<int:pk>/results/', base_views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote/', base_views.vote, name='vote'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='Publised recently?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)


class Post(models.Model):
    title = models.CharField(max_length=50)
    text = models.TextField()

    def __str__(self):
        return self.text


class Reply(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=1000)
    # reples = models.ForeignKey('Comment', on_delete=models.CASCADE, related_name="replies", null=True)

polls/forms.py
from django import forms

from polls.models import Question, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': 'comment content',
        }

polls/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from rest_framework import viewsets
from ..serializers import QuestionSerializer

from ..models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

# def index(request):
#     # input parameter
#     page = request.GET.get('page', '1')  # page
#     # select
#     # latest_question_list = Question.objects.order_by('pub_date')
#     latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
#     # paging
#     paginator = Paginator(latest_question_list, 5)  # show 5 question per page
#     page_obj = paginator.get_page(page)
#
#     context = {'latest_question_list': page_obj}
#     return render(request, "polls/index.html", context)

def detail(request, question_id):
    """
    poll print question detail
    """
    question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()), pk=question_id)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def result(request, question_id):
    """
    poll result
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, "polls/results.html", context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += F('votes') + 1
        selected_choice.save()

        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

# API
class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

polls/views/comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone


from ..forms import CommentForm
from ..models import Question, Comment

@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
    polls register comment on question
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('polls:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'polls/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
    polls modify comment on question
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, 'There is no authority to modify')
        return redirect('polls:detail', question_id=comment.question.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('polls:detail', question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'polls/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
    polls delete comment on question
    """
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, 'There is no authority to delete')
        return redirect('polls:detail', question_id=comment.question_id)
    else:
        comment.delete()
        messages.success(request, 'Delete comment success')
    return redirect('polls:detail', question_id=comment.question_id)



# def post_detail(request, slug):
#     post = Post.objects.get(slug=slug)
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             reply_obj = None
#             try:
#                 reply_id = int(request.POST.get('reply_id'))
#             except:
#                 reply_id = None
#             if reply_id:
#                 reply_obj = Comment.objects.get(id=reply_id)
#
#             author = form.cleaned_data['author']
#             comment = form.cleaned_data['comment']
#             if reply_obj:
#                Comment(author=author,comment_field=comment, reply=reply_obj, post=post).save()
#             else:
#                 Comment(author=author,comment_field=comment, post=post).save()
#             return redirect(reverse('post_detail', args=[post.slug]))
#     else:
#         form = CommentForm()
#     comments = Comment.objects.filter(post=post, reply=None).order_by('-create_date')
#     context = {
#         'post':post,
#         'form':form,
#         'comments':comments
#     }
#     return render(request, 'post_detail.html', context)

templates/polls/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">Register Comment</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">Comment content</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/polls/detail.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
<!-- Comment on Question Start -->
{% if question.comment_set.count > 0 %}
<div class="mt-3">
{% for comment in question.comment_set.all %}
    <div class="comment py-2 text-muted">
        <span style="white-space: pre-line;">{{ comment.content }}</span>
        <span>
            - {{ comment.author }}, {{ comment.create_date }}
            {% if comment.modify_date %}
                (Revise:{{ comment.modify_date }})
            {% endif %}
        </span>
        {% if request.user == comment.author %}
            <a href="{% url 'polls:comment_modify_question' comment.id  %}" class="small">Revise</a>,
            <a href="{% url 'polls:comment_delete_question' comment.id  %}" class="small delete">Delete</a>
        {% endif %}
    </div>
    <!-- reply start -->
    {% for reply in comment.replies.all %}
        <div class="comment py-3 text-muted">
            <span>
                - {{ reply.author }}, {{ reply.create_date }}
                {% if reply.modify_date %}
                    (Revise:{{ reply.modify_date }})
                {% endif %}
            </span>
            {% if request.user == reply.author %}
                <a href="{% url 'polls:comment_modify_question' reply.id  %}" class="small">Revise</a>,
                <a href="{% url 'polls:comment_delete_question' reply.id  %}" class="small delete">Delete</a>
            {% endif %}
        </div>
    {% endfor %}
    <!-- reply end -->
{% endfor %}
</div>
{% endif %}
<div>
    <a href="{% url 'polls:comment_create_question' question.id  %}"
       class="small"><small>Add Comment ..</small></a>
</div>
<!-- Comment on Question End -->
</form>
{% endblock %}

templates/polls/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dart">
            <th>No.</th>
            <th>Subject</th>
            <th>Date</th>
        </tr>
        </thead>
        <tbody>
        {% if latest_question_list %}
            {% for question in latest_question_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'polls:detail' question.id %}">
                        {{ question.question_text }}
                    </a>
                </td>
                <td>{{ question.pub_date }}</td>
            </tr>
            {% endfor %}
            </ul>
        {% else %}
            <tr>
                <td colspan="3">No polls are available.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>


<!--    &lt;!&ndash; paging not well done Check!!!!! &ndash;&gt;-->
<!--    &lt;!&ndash; paging start &ndash;&gt;-->
<!--    <ul class="pagination justify-content-center">-->
<!--        &lt;!&ndash; Before page &ndash;&gt;-->
<!--        {% if latest_question_list.has_previous %}-->
<!--        <li class="page-item">-->
<!--            <a class="page-link" href="?page={{ latest_question_list.previous_page_number }}">Before</a>-->
<!--        </li>-->
<!--        {% else %}-->
<!--        <li class="page-item disabled">-->
<!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Before</a>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--        &lt;!&ndash; page list &ndash;&gt;-->
<!--        {% for page_number in latest_question_list.paginator.page_range %}-->
<!--        {% if page_number >= latest_question_list.number|add:-5 and page_number <= latest_question_list.number|add:5 %}-->
<!--            {% if page_number == latest_question_list.number %}-->
<!--            <li class="page-item active" aria-current="page">-->
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
<!--            </li>-->
<!--            {% else %}-->
<!--            <li class="page-item">-->
<!--                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>-->
<!--            </li>-->
<!--            {% endif %}-->
<!--        {% endif %}-->
<!--        {% endfor %}-->
<!--        &lt;!&ndash; After page &ndash;&gt;-->
<!--        {% if latest_question_list.has_next %}-->
<!--        <li class="page-item">-->
<!--            <a class="page-link" href="?page={{ latest_question_list.next_page_number }}">After</a>-->
<!--        </li>-->
<!--        {% else %}-->
<!--        <li class="page-item disabled">-->
<!--            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">After</a>-->
<!--        </li>-->
<!--        {% endif %}-->
<!--    </ul>-->
<!--    &lt;!&ndash; paging end &ndash;&gt;-->

</div>
{% endblock %}

templates/polls/results.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}