common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/',
         auth_views.LoginView.as_view(template_name='common/login.html'),
         name='login'),

    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

hamji/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from polls.views import base_views

from . import views

router = routers.DefaultRouter()
router.register(r"users", views.UserViewSet)
router.register(r"questions", base_views.QuestionViewSet)

urlpatterns = [
    path("_api/", include(router.urls)),
    path("polls/", include("polls.urls")),
    path("common/", include("common.urls")),
    path("admin/", admin.site.urls),
    # path("", base_views.index, name='index'),
]

polls/urls.py
from django.urls import path
from .views import base_views, comment_views
from . import views

app_name = 'polls'
urlpatterns = [
    # base_views.py
    # path('', base_views.index, name='index'),
    path('', base_views.IndexView.as_view(), name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    # path('<int:pk>', base_views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/results/', base_views.result, name='results'),
    # path('<int:pk>/results/', base_views.ResultView.as_view(), name='results'),
    path('<int:question_id>/vote/', base_views.vote, name='vote'),

    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
]

polls/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from rest_framework import viewsets
from ..serializers import QuestionSerializer

from ..models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

# def index(request):
#     # input parameter
#     page = request.GET.get('page', '1')  # page
#     # select
#     # latest_question_list = Question.objects.order_by('pub_date')
#     latest_question_list = Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')
#     # paging
#     paginator = Paginator(latest_question_list, 5)  # show 5 question per page
#     page_obj = paginator.get_page(page)
#
#     context = {'latest_question_list': page_obj}
#     return render(request, "polls/index.html", context)

def detail(request, question_id):
    """
    poll print question detail
    """
    question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()), pk=question_id)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def result(request, question_id):
    """
    poll result
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, "polls/results.html", context)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += F('votes') + 1
        selected_choice.save()

        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

# API
class QuestionViewSet(viewsets.ModelViewSet):
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Meta tags -->
    <meta charset="utf-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- poll CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Welcome! Choose Subject</title>
</head>
<body>
<!-- navigation bar -->
{% include "navbar.html" %}
<!-- information in base template start -->
{% block content %}
{% endblock %}
<!-- information in base template end -->
<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- print field error -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- print non_field error -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- navigation bar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'polls:index' %}">Tridge</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %}
                <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (Logout)</a>
                {% else %}
                <a class="nav-link" href="{% url 'common:login' %}">Login</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>